"""rename_profile_to_users_and_add_auth

Revision ID: 8d2773e05041
Revises: 4c44e1f5ed89
Create Date: 2026-02-26 15:15:24.713948

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d2773e05041'
down_revision: Union[str, Sequence[str], None] = '4c44e1f5ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM chat_messages')
    op.execute('DELETE FROM chat_conversations')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column(
        'occupation', 
        sa.Enum(
            'PHYSICIAN', 'NURSE', 'PHARMACIST', 'SURGEON', 'MEDICAL_STUDENT', 
            'RESEARCHER', 'OTHER', name='clinicaloccupation'
        ), 
        nullable=True
    ),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(
        'chat_conversations_user_id_fkey', 'chat_conversations', type_='foreignkey'
    )
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.create_foreign_key(
        'chat_conversations_user_id_fkey', 
        'chat_conversations', 
        'users', 
        ['user_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_conversations', type_='foreignkey')
    op.create_foreign_key(
        op.f('chat_conversations_user_id_fkey'), 
        'chat_conversations', 
        'profiles', 
        ['user_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
